stages:
  dataset:
    cmd : python src/dataset.py
    deps:
      - data/raw/Delivery Dataset.csv
      - src/dataset.py
    outs:
      - data/processed/cleaned Delivery Dataset.csv

  data_preparation:
    cmd: python src/data_preparation.py
    deps:
      - data/processed/cleaned Delivery Dataset.csv
      - src/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv
  
  feature_engineering:
    cmd : python src/features.py
    deps:
      - data/interim/train.csv
      - data/interim/test.csv
      - src/features.py
    outs:
      - data/processed/train_features/train_labels.csv
      - data/processed/test_features/test_labels.csv
      - data/processed/train_features/train_trans.csv
      - data/processed/test_features/test_trans.csv
      - models/preprocessor.joblib

  model_training:
    cmd : python src/modeling/train.py
    deps:
      - data/processed/train_features/train_trans.csv
      - data/processed/train_features/train_labels.csv
      - src/modeling/train.py
    params:
      - Train.RandomForest
      - Train.XGB_BOOST
    outs:
      - models/model.joblib
